---
engine: julia
---

# File format for output of ChatGPT analysis

Each article in Lewis-Short is represented by a one-line delimited-text file with six columns separated by the pipe character `|`. The six columns represent:

1. a sequence number in Lewis-Short. This can be used to sort a selection of entries into the original alphabetic sequence of Lewis-Short.
2. a Cite2Urn for the article.
3. a dictionary headword, or lemma.
4. a brief English definition.
5. identification of the part of speech.
6. morphological information.

The sixth column contains a comma-delimited list of information that varies depending on the part of speech. 

- for verbs: 4 items, the conjugation followed by three principal parts
- for nouns: 3 items, nominative singular, genitive singular and gender
- for adjectives: 3 items, the nominative singular of masculine, feminine and neuter forms 
- for prepositions, a list of 1 or more cases the preposition can be constructed with 
- for other parts of speech, the label "uninflected"


**Example**: data line recording ChatGPT's summary of the verb *offero*:


`32377|urn:cite2:hmt:ls.markdown:n32374|offĕro|to bring before; to present, offer; to show|verb (compound)|3, offĕro, obtŭli, oblātum`