project:
  type: website
jupyter: julia-1.10  
theme: spacelab
execute:
  freeze: auto
date: last-modified  
margin-header: "Package version: `0.4.0`"

format:
  html: 
    toc: true


website:
  
  title: "lexiconmining"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Concepts"
        file: concepts/index.qmd         
      - text: "Tutorials"
        file: tutorials/index.qmd          
      - text: "Recipes"
        file: guides/index.qmd           
      - text: "Reference"
        file: reference/index.qmd 
      - text: "Data audits"
        file: audits/index.qmd
    right:   
      - icon: github
        href: https://github.com/neelsmith/LexiconMining.jl
        aria-label: GitHub
      - icon: person-circle
        menu:
          - text: "Neel Smith: digital scholarship"
            href: https://neelsmith.quarto.pub
        aria-label: "More of my work"
  sidebar:
    - title: "Concepts"
      contents: 
        - concepts/index.qmd
        - concepts/orthographies.qmd
        - concepts/cgpt.qmd 
    - title: "Tutorials"
      contents: 
        - tutorials/index.qmd           
        - tutorials/readsummaries.qmd           
    - title: "Recipes"
      contents: 
        - guides/index.qmd  
        - guides/objectmodel.qmd                  
    - title: "Reference"
      contents: 
        - reference/index.qmd  
        - reference/prompt.qmd         
        - reference/delimited.qmd         
        - reference/postprocessing.qmd
        - reference/datasets.qmd
    - title: "Data audits"
      contents: 
        - audits/index.qmd
        - audits/step1-originalqueries/index.qmd
        - audits/step2-summaries/index.qmd
        - audits/step3-pos/index.qmd